env                           = "dev"
deployer_service_account      = "" # se pasa desde el flujo (vars.GCP_DEPLOYER_SA_DEV)
db_tier                       = "db-g1-small"
db_ha                         = false
db_disk_gb                    = 10
redis_tier                    = "BASIC"
api_min_instances             = 0
api_public_ingress            = true
allow_unauthenticated_invoker = false # true cuando el dueño exceptúe la política de organización (tareas del dueño)
worker_min_instances          = 1
synthetic_enabled             = true
payments_provider             = "fake"
push_provider                 = "log"
staff_bootstrap_email         = "santiago.bernal@supercargadores.co"
cloud_armor_enabled           = false
alert_emails                  = ["santiago.bernal@supercargadores.co"]
public_dns_ready              = false
gateway_replicas              = 1
gateway_max_replicas          = 3
gateway_cpu                   = "250m"
gateway_memory                = "512Mi"
