env                           = "dev"
deployer_service_account      = "" # se pasa desde el flujo (vars.GCP_DEPLOYER_SA_DEV)
db_tier                       = "db-g1-small"
db_ha                         = false
db_disk_gb                    = 10
redis_tier                    = "BASIC"
api_min_instances             = 0
api_public_ingress            = true
allow_unauthenticated_invoker = true # excepción a Domain restricted sharing aplicada el 29-09-2026
worker_min_instances          = 1
synthetic_enabled             = false # apagado el 02-10-2026 para contener costos (ADR 0038): las pruebas de carga se hacen en staging
synthetic_visible_in_app      = false
payments_provider             = "fake"
push_provider                 = "log"
sms_provider                  = "brevo"                  # SMS reales con Brevo desde el 01-10-2026 (9j); misma clave que el correo
sms_api_key_secret            = "email-provider-api-key" # la clave de Brevo sirve para correo y SMS
sms_sender                    = "VOLT"
google_maps_map_id            = "752cbbfca729c761217f4d4d" # volt-web-dev (9c, 30-09-2026)
email_provider                = "brevo"                    # clave en email-provider-api-key cargada por el dueño el 01-10-2026 (9d, ADR 0032)
staff_bootstrap_email         = "santiago.bernal@supercargadores.co"
cloud_armor_enabled           = false
alert_emails                  = ["santiago.bernal@supercargadores.co"]
public_dns_ready              = true # DNS y certificados activos el 29-09-2026: uptime checks y alertas encendidos
gateway_replicas              = 1
gateway_max_replicas          = 3
gateway_cpu                   = "250m"
gateway_memory                = "512Mi"
