env                           = "dev"
deployer_service_account      = "" # se pasa desde el flujo (vars.GCP_DEPLOYER_SA_DEV)
db_tier                       = "db-g1-small"
db_ha                         = false
db_disk_gb                    = 10
redis_tier                    = "BASIC"
api_min_instances             = 0
api_public_ingress            = true
allow_unauthenticated_invoker = true # excepción a Domain restricted sharing aplicada el 29-09-2026
worker_min_instances          = 1
synthetic_enabled             = true
synthetic_visible_in_app      = true # estación de pruebas visible en la app (iteración 9)
payments_provider             = "fake"
push_provider                 = "log"
sms_provider                  = "fake"                     # el código de verificación del celular vuelve en la respuesta (ADR 0031)
google_maps_map_id            = "752cbbfca729c761217f4d4d" # volt-web-dev (9c, 30-09-2026)
email_provider                = "brevo"                    # clave en email-provider-api-key cargada por el dueño el 01-10-2026 (9d, ADR 0032)
staff_bootstrap_email         = "santiago.bernal@supercargadores.co"
cloud_armor_enabled           = false
alert_emails                  = ["santiago.bernal@supercargadores.co"]
public_dns_ready              = true # DNS y certificados activos el 29-09-2026: uptime checks y alertas encendidos
gateway_replicas              = 1
gateway_max_replicas          = 3
gateway_cpu                   = "250m"
gateway_memory                = "512Mi"
