env                           = "prod"
deployer_service_account      = "" # se pasa desde el flujo (vars.GCP_DEPLOYER_SA_PROD)
db_tier                       = "db-custom-2-8192"
db_ha                         = false # HA regional cuando haya cargadores reales (ARQ §7)
db_disk_gb                    = 50
redis_tier                    = "STANDARD_HA"
api_min_instances             = 1
api_public_ingress            = false
allow_unauthenticated_invoker = true # excepción a Domain restricted sharing aplicada el 29-09-2026
worker_min_instances          = 1
synthetic_enabled             = true
payments_provider             = "wompi"
wompi_environment             = "production"
push_provider                 = "expo"
staff_bootstrap_email         = "santiago.bernal@supercargadores.co"
cloud_armor_enabled           = true
alert_emails                  = ["santiago.bernal@supercargadores.co"]
public_dns_ready              = false
audit_bucket_locked           = false # se bloquea (irreversible) cuando el dueño lo apruebe
gateway_replicas              = 2
gateway_max_replicas          = 10
gateway_cpu                   = "500m"
gateway_memory                = "1Gi"
