env                           = "staging"
deployer_service_account      = "" # se pasa desde el flujo (vars.GCP_DEPLOYER_SA_STAGING)
db_tier                       = "db-custom-1-3840"
db_ha                         = false
db_disk_gb                    = 20
redis_tier                    = "BASIC"
api_min_instances             = 1
api_public_ingress            = false
allow_unauthenticated_invoker = true # excepción a Domain restricted sharing aplicada el 29-09-2026
worker_min_instances          = 1
synthetic_enabled             = true
payments_provider             = "wompi"
wompi_environment             = "sandbox"
push_provider                 = "expo"
staff_bootstrap_email         = "santiago.bernal@supercargadores.co"
cloud_armor_enabled           = true
alert_emails                  = ["santiago.bernal@supercargadores.co"]
public_dns_ready              = false
gateway_replicas              = 2
gateway_max_replicas          = 5
gateway_cpu                   = "500m"
gateway_memory                = "1Gi"
