env                           = "staging"
deployer_service_account      = ""            # se pasa desde el flujo (vars.GCP_DEPLOYER_SA_STAGING)
db_tier                       = "db-g1-small" # reducido el 02-10-2026 (ADR 0038); prod se dimensiona aparte
db_ha                         = false
db_disk_gb                    = 20
redis_tier                    = "BASIC"
api_min_instances             = 1 # se mantiene: es el ambiente que prueba el dueño desde las apps
api_public_ingress            = false
allow_unauthenticated_invoker = true # excepción a Domain restricted sharing aplicada el 29-09-2026
worker_min_instances          = 1
synthetic_enabled             = true
synthetic_visible_in_app      = true # estación de pruebas visible en la app (iteración 9)
payments_provider             = "wompi"
wompi_environment             = "sandbox"
push_provider                 = "expo"
sms_provider                  = "brevo"                  # SMS reales con Brevo desde el 02-10-2026 (9j): el dueño contrató el plan de SMS
sms_api_key_secret            = "email-provider-api-key" # la clave de Brevo sirve para correo y SMS
sms_sender                    = "VOLT"
google_maps_map_id            = "daa44820e1adebb18baf61f0" # volt-web-staging (9c, 30-09-2026)
email_provider                = "brevo"                    # clave en email-provider-api-key cargada por el dueño el 01-10-2026 (9d, ADR 0032)
staff_bootstrap_email         = "santiago.bernal@supercargadores.co"
cloud_armor_enabled           = true
static_egress_ip              = true # IP fija de salida (Cloud NAT) desde el 01-10-2026: Wompi rechazaba las IP variables de Cloud Run
alert_emails                  = ["santiago.bernal@supercargadores.co"]
public_dns_ready              = true # DNS y certificados activos el 29-09-2026: uptime checks y alertas encendidos
gateway_replicas              = 1    # un pod del tamaño mínimo de Autopilot hasta la prueba de carga de la iteración 10 (ADR 0038)
gateway_max_replicas          = 3
gateway_cpu                   = "250m"
gateway_memory                = "512Mi"
