// Archivo generado por infra/identity/build-templates.mjs a partir de infra/identity/templates.
// No editar a mano: cambia la plantilla HTML y vuelve a ejecutar el script.
import type { EmailTemplate, EmailTemplateKind } from './email.ts';

export const EMAIL_TEMPLATES: Record<EmailTemplateKind, EmailTemplate> = {
  'verify-email': {
    subject: "Confirme su correo en VOLT",
    html: "<!doctype html>\n<html lang=\"es\">\n  <head>\n    <meta charset=\"utf-8\" />\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\n    <title>Confirme su correo</title>\n  </head>\n  <body style=\"margin:0;padding:24px 12px;background:#f5f5f5;font-family:Roboto,Arial,'Helvetica Neue',sans-serif;color:#0b0b0b;\">\n    <table role=\"presentation\" width=\"100%\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\">\n      <tr>\n        <td align=\"center\">\n          <table role=\"presentation\" width=\"100%\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\" style=\"max-width:560px;background:#ffffff;border-radius:12px;overflow:hidden;border:1px solid #e5e5e5;\">\n            <tr>\n              <td style=\"background:#dc2626;padding:20px 28px;\">\n                <img src=\"https://{{APP_HOST}}/brand/volt-logo-blanco.png\" width=\"132\" height=\"56\" alt=\"VOLT\" style=\"display:block;border:0;width:132px;height:auto;\" />\n              </td>\n            </tr>\n            <tr>\n              <td style=\"padding:28px 28px 8px;\">\n                <h1 style=\"margin:0 0 12px;font-size:24px;line-height:1.2;font-weight:700;color:#0b0b0b;\">Confirme su correo</h1>\n                <p style=\"margin:0 0 20px;font-size:16px;line-height:1.5;color:#0b0b0b;\">Le damos la bienvenida a VOLT. Confirme que %EMAIL% es su correo para cargar su vehículo con precio claro antes de conectar y cobro al terminar.</p>\n                <table role=\"presentation\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\">\n                  <tr>\n                    <td style=\"background:#dc2626;border-radius:6px;\">\n                      <a href=\"%LINK%\" style=\"display:inline-block;padding:14px 24px;font-size:15px;font-weight:700;letter-spacing:0.5px;text-transform:uppercase;color:#ffffff;text-decoration:none;\">Confirmar correo</a>\n                    </td>\n                  </tr>\n                </table>\n                <p style=\"margin:20px 0 0;font-size:13px;line-height:1.5;color:#525252;\">Si el botón no funciona, copie este enlace en el navegador:<br /><a href=\"%LINK%\" style=\"color:#b91c1c;word-break:break-all;\">%LINK%</a></p>\n              </td>\n            </tr>\n            <tr>\n              <td style=\"padding:16px 28px 28px;\">\n                <p style=\"margin:0;font-size:13px;line-height:1.5;color:#525252;\">Si no creó una cuenta en VOLT, ignore este correo: no pasará nada.</p>\n              </td>\n            </tr>\n            <tr>\n              <td style=\"padding:16px 28px;border-top:1px solid #e5e5e5;font-size:12px;line-height:1.5;color:#737373;\">\n                VOLT es una marca de Supercargadores Vehiculares S.A.S. · Este correo se envió a %EMAIL% desde un sistema automático; no responda a este mensaje.\n              </td>\n            </tr>\n          </table>\n        </td>\n      </tr>\n    </table>\n  </body>\n</html>\n",
  },
  'reset-password': {
    subject: "Cree una contraseña nueva en VOLT",
    html: "<!doctype html>\n<html lang=\"es\">\n  <head>\n    <meta charset=\"utf-8\" />\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\n    <title>Cree una contraseña nueva</title>\n  </head>\n  <body style=\"margin:0;padding:24px 12px;background:#f5f5f5;font-family:Roboto,Arial,'Helvetica Neue',sans-serif;color:#0b0b0b;\">\n    <table role=\"presentation\" width=\"100%\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\">\n      <tr>\n        <td align=\"center\">\n          <table role=\"presentation\" width=\"100%\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\" style=\"max-width:560px;background:#ffffff;border-radius:12px;overflow:hidden;border:1px solid #e5e5e5;\">\n            <tr>\n              <td style=\"background:#dc2626;padding:20px 28px;\">\n                <img src=\"https://{{APP_HOST}}/brand/volt-logo-blanco.png\" width=\"132\" height=\"56\" alt=\"VOLT\" style=\"display:block;border:0;width:132px;height:auto;\" />\n              </td>\n            </tr>\n            <tr>\n              <td style=\"padding:28px 28px 8px;\">\n                <h1 style=\"margin:0 0 12px;font-size:24px;line-height:1.2;font-weight:700;color:#0b0b0b;\">Cree una contraseña nueva</h1>\n                <p style=\"margin:0 0 20px;font-size:16px;line-height:1.5;color:#0b0b0b;\">Recibimos una solicitud para restablecer la contraseña de %EMAIL%. Pulse el botón y escriba una contraseña nueva de al menos 8 caracteres.</p>\n                <table role=\"presentation\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\">\n                  <tr>\n                    <td style=\"background:#dc2626;border-radius:6px;\">\n                      <a href=\"%LINK%\" style=\"display:inline-block;padding:14px 24px;font-size:15px;font-weight:700;letter-spacing:0.5px;text-transform:uppercase;color:#ffffff;text-decoration:none;\">Crear contraseña</a>\n                    </td>\n                  </tr>\n                </table>\n                <p style=\"margin:20px 0 0;font-size:13px;line-height:1.5;color:#525252;\">Si el botón no funciona, copie este enlace en el navegador:<br /><a href=\"%LINK%\" style=\"color:#b91c1c;word-break:break-all;\">%LINK%</a></p>\n              </td>\n            </tr>\n            <tr>\n              <td style=\"padding:16px 28px 28px;\">\n                <p style=\"margin:0;font-size:13px;line-height:1.5;color:#525252;\">Si no pidió cambiar la contraseña, ignore este correo: su contraseña actual sigue vigente.</p>\n              </td>\n            </tr>\n            <tr>\n              <td style=\"padding:16px 28px;border-top:1px solid #e5e5e5;font-size:12px;line-height:1.5;color:#737373;\">\n                VOLT es una marca de Supercargadores Vehiculares S.A.S. · Este correo se envió a %EMAIL% desde un sistema automático; no responda a este mensaje.\n              </td>\n            </tr>\n          </table>\n        </td>\n      </tr>\n    </table>\n  </body>\n</html>\n",
  },
};
